### ISSUE TITLE
Update Spring Boot

### ISSUE THREAD

**Issue by josdem** [josdem/jmailer-spring-boot#39]
**Todo**
- Update Spring version to 2.7.0

**Comment by mslowiak** [comment]
hi, can I grab this one? :) 
Newest version for 2.x is 2.7.10.
Do you have also plan to migrate to 3.x?

**Comment by josdem** [comment]
Hi mslowiak, you are welcome! 
I appreciate that you want to contribute to this repository:
- 2.7.10 it is okay
- 3.0.1 (desirable)
Always having the latest version is the goal :100: 
Let me know if you have any doubts about the setup. All information is on the [wiki](https://github.com/josdem/jmailer-spring-boot/wiki) page.
