### ISSUE TITLE
Create a Jenkins pipeline to deploy automatically the service

### ISSUE THREAD

**Issue by josdem** [josdem/jmailer-spring-boot#50]
**Todo**
- Create SSH key to authenticate jenkins server to the jmailer host server
- Create a Jenkins job to build and deploy
- Create Jenkins pipeline file to define stages, see this project as reference: [jugoterapia-services-pipeline](https://github.com/josdem/jugoterapia-services-pipeline)

**Comment by mslowiak** [comment]
@josdem Do you have any machine that will host Jenkins and expose Jenkins publicly?

**Comment by josdem** [comment]
Hi @mslowiak, yes, I have a VM in Google Cloud: https://jenkins.josdem.io/. Let me know if you would like to have access to Jenkins and take a look at the Jenkins pipeline; still working on it tho

**Comment by josdem** [comment]
Hello @mslowiak, this ticket is done, and it is working fine; please take a look at the `Jenkinsfile` if you would like to see the implementation. https://github.com/josdem/jmailer-pipeline

**Comment by mslowiak** [comment]
@josdem 
Sry for lack of response. 

I do not get how it is suppose to work and have couple of questions:
1. Why steps like `Stop Jmailer` and `Remove Jmailer` are needed?
2. What is the reason to have `Move Jmailer` and `Start Jmailer`?
3. Where can I see the `jmailer-spring-boot` job definition?

**Comment by josdem** [comment]
Hi @mslowiak, here my answers:
1. `Stop Jmailer` is a simple command: `sudo systemctl stop jmailer` also `Remove Jmailer` is a `rm /opt/jmailer.jar`
2. Move and Start Jmailer are similar Linux commands: `mv` and `sudo systemctl start jmailer`
3. `jmailer-spring-boot` definition is a Gradle Jenkins job that does the test and build tasks as you can do from your local computer.

If you want to know more about how to create shell scripts in Jenkins go here: https://josdem.io/techtalk/cicd/jenkins_shell_execution/

If you want to see `jmailer-spring-boot` in Jenkins I need to create a user for you in the server, happy to do it just please confirm you want that.

**Comment by mslowiak** [comment]
Yes, you can create a user for me with read only privileges.
You can use my email:  marcin.slowiak.007@gmail.com

**Comment by josdem** [comment]
Okay, I will do.
