### ISSUE TITLE
Add code formatter

### ISSUE THREAD

**Issue by josdem** [josdem/jmailer-spring-boot#78]
As **a developer**, I want to have a code formatted **so that** I can format the code before pushing it to the repository.

**Acceptance Criteria**
- I am able to see [Spotless](https://github.com/diffplug/spotless) configuration
- I am able to format the code automatically when  test cases run

**References**
- https://plugins.gradle.org/plugin/com.diffplug.spotless
- https://github.com/josdem/fruitypedia-spring-boot/blob/main/build.gradle

**Comment by Atharv3221** [comment]
Hi, I'd like to work on this issue. I'II start by  adding a code formatter and submitting a pull request.

**Comment by josdem** [comment]
> Hi, I'd like to work on this issue. I'II start by  adding a code formatter and submitting a pull request.

Hi @Atharv3221 I appreciate you want to work on this issue, however we already have a PR, please take a look: https://github.com/josdem/jmailer-spring-boot/pull/79

**Comment by Atharv3221** [comment]
Thank you for the update! @josdem

**Comment by josdem** [comment]
PR merged: https://github.com/josdem/jmailer-spring-boot/pull/79
